-- Script SQL para insertar preguntas en la base de datos DefensaIA (Parte 1)
-- Solo inserta datos, no modifica la estructura de las tablas

-- Insertar preguntas y respuestas directamente (Primeras 20 preguntas)
INSERT INTO faq (id, q, a) VALUES
(gen_random_uuid(), '¿Cuál es el horario de trabajo oficial de los servidores públicos de la Cámara de Diputados?', 'La jornada laboral es de 8 horas diarias, de lunes a viernes. El horario establecido es de 08:30 a 12:30 por la mañana y de 14:30 a 18:30 por la tarde. Este horario puede prolongarse según las necesidades institucionales sin remuneración adicional.'),
(gen_random_uuid(), '¿Se permite alguna tolerancia al horario de ingreso?', 'Sí, se concede una tolerancia diaria de 10 minutos. Esta se distribuye en 5 minutos por la mañana (hasta las 08:35) y 5 minutos por la tarde (hasta las 14:35).'),
(gen_random_uuid(), '¿Cómo se gestionan los atrasos?', 'Pasado el tiempo de tolerancia, los minutos acumulados de retraso se sumarán y computarán para aplicar las sanciones correspondientes.'),
(gen_random_uuid(), '¿Existe alguna tolerancia especial para estudiantes o docentes?', 'Sí, los servidores públicos que sean docentes o estudiantes de educación superior pueden gozar de una tolerancia de hasta dos horas diarias con goce de haberes, previa justificación documentada.'),
(gen_random_uuid(), '¿Cómo se solicita un permiso personal?', 'Un permiso personal es una autorización para ausentarse durante la jornada laboral por motivos personales, con el 100% de la remuneración, y debe ser otorgado por un superior inmediato o una autoridad superior.'),
(gen_random_uuid(), '¿Qué es una declaratoria en comisión?', 'Es una autorización para que un servidor público realice una misión oficial específica fuera de su lugar de trabajo habitual, de manera temporal y con el 100% de su remuneración.'),
(gen_random_uuid(), '¿Puedo solicitar un permiso para asistir a seminarios o cursos?', 'Sí, se puede solicitar una "Comisión de Estudios", que es una autorización temporal para asistir a seminarios, cursos de postgrado o actualizaciones de conocimiento, dentro o fuera del país, la cual se concede mediante una resolución expresa.'),
(gen_random_uuid(), '¿Cuál es la escala de vacaciones en función de la antigüedad?', 'La escala es la siguiente: De 1 año y 1 día a 5 años de antigüedad: 15 días hábiles. De 5 años y 1 día a 10 años de antigüedad: 20 días hábiles. De 10 años y 1 día o más: 30 días hábiles.'),
(gen_random_uuid(), '¿Cómo se programan las vacaciones anuales?', 'La Dirección de Recursos Humanos es responsable de elaborar un cronograma general de vacaciones para el año siguiente durante la segunda quincena de noviembre.'),
(gen_random_uuid(), '¿Es posible que se interrumpan mis vacaciones?', 'Sí, la Máxima Autoridad Ejecutiva puede ordenar la interrupción de las vacaciones por razones excepcionales de interés institucional.'),
(gen_random_uuid(), '¿Cómo es el proceso de contratación de nuevo personal?', 'La contratación se rige por el Subsistema de Dotación de Personal, el cual incluye procesos de cuantificación de la demanda, análisis de la oferta interna de personal y, si es necesario, convocatorias públicas externas.'),
(gen_random_uuid(), '¿Qué es el Sistema de Administración de Personal (SAP)?', 'El SAP es un sistema estructurado en varios subsistemas, incluyendo la dotación, la evaluación del desempeño, la movilidad de personal y el retiro. Su objetivo es gestionar eficientemente los recursos humanos de la entidad.'),
(gen_random_uuid(), '¿Las promociones o ascensos son automáticos?', 'No, los ascensos están basados en la meritocracia. La promoción es el resultado del merecimiento obtenido a lo largo de la carrera y se realiza conforme a la regulación específica.'),
(gen_random_uuid(), '¿Qué se evalúa en el desempeño de un funcionario?', 'El proceso de evaluación del desempeño considera factores como la adaptabilidad, la iniciativa, las relaciones interpersonales, la capacidad técnica, la responsabilidad, la conducta y la eficiencia en el logro de resultados.'),
(gen_random_uuid(), '¿Cuáles son algunas de las prohibiciones clave para los servidores públicos?', 'Entre las prohibiciones se encuentran: ejercer funciones ajenas a su competencia, realizar actividades político-partidarias durante la jornada de trabajo, registrar la asistencia de otro servidor público, fumar o consumir alimentos en áreas no autorizadas, y portar armas.'),
(gen_random_uuid(), '¿Cuál es el procedimiento para solicitar viáticos para una misión oficial?', 'Para solicitar viáticos, los servidores públicos deben adjuntar una nota de solicitud, el itinerario, la invitación (si corresponde), la liquidación de viáticos y una certificación presupuestaria.'),
(gen_random_uuid(), '¿Qué escala de viáticos aplica para viajes al interior del país?', 'La escala de viáticos para viajes nacionales se basa en la categoría del funcionario, conforme al Decreto Supremo N° 1788. Varía si el viaje es interdepartamental, intradepartamental o a la franja de frontera.'),
(gen_random_uuid(), '¿Existe un plazo para la presentación de los descargos de viáticos?', 'Sí, los servidores públicos tienen un plazo máximo de ocho días hábiles después de su retorno para presentar su informe escrito de descargo de pasajes y viáticos. Si no lo hacen, los gastos serán considerados personales y se descontarán de su salario.'),
(gen_random_uuid(), '¿Se pueden pagar viáticos por fines de semana o feriados?', 'El pago de viáticos por fines de semana o feriados está prohibido, a menos que se justifique con las actividades oficiales o si la comisión dura más de seis días hábiles continuos.'),
(gen_random_uuid(), '¿Qué sucede si el hospedaje o la alimentación son cubiertos por un tercero?', 'Si un organismo externo cubre los gastos, el servidor público recibirá un porcentaje del viático total: 70% si solo cubre el hospedaje, y 25% si cubre tanto el hospedaje como la alimentación.');

-- Continuar con la Parte 2
